import './globals.css'
import Nav from '/components/Nav/Nav'
import Footer from '/components/Footer/Footer';
import { Providers } from "../redux/provider"
import AuthProviders from '../components/AuthProviders';
export const metadata = {
  title: 'food',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthProviders>
            <Nav />
            {children}
            <Footer />
          </AuthProviders>
        </Providers>
      </body>
    </html>
  )
}
